---
subsetName: default subset
description: basic test
nbConfigs: '3'
configuration:
    - ref: default
      test: default
    - ref: default 
      test: bcstc
    - ref: newProcessors
      test: bcstc
